[package]
name = "xml2saty"
version = "0.1.0"
authors = ["puripuri2100 <puripuri2100@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#xmlparser = "0.13.0"
xml-rs = "0.8"
clap = "2.20.3"
json = "0.12.1"